// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Lesson is the predicate function for lesson builders.
type Lesson func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)
